---
apiVersion: v1
kind: Service
metadata:
  name: scraperr
spec:
  type: NodePort
  selector:
    app: scraperr
  ports:
    - port: {{ .Values.scraperr.servicePort }}
      targetPort: {{ .Values.scraperr.containerPort }}
      nodePort: {{ .Values.scraperr.nodePort }}

---
apiVersion: v1
kind: Service
metadata:
  name: scraperr-api
spec:
  type: ClusterIP
  selector:
    app: scraperr-api
  ports:
    - port: 8000
      targetPort: {{ .Values.scraperrApi.containerPort }}
