scraperr:
  image:
    repository: jpyles0524/scraperr
    tag: latest
    pullPolicy: IfNotPresent
  containerCommand: ["npm", "run","start"]
  containerPort: 3000
  servicePort: 80
  nodePort: 32300
  env:
    - name: NEXT_PUBLIC_API_URL
      value: "http://scraperr-api:8000"
    - name: SERVER_URL
      value: "http://scraperr-api:8000"

scraperrApi:

  image:
    repository: jpyles0524/scraperr_api
    tag: latest
    pullPolicy: IfNotPresent
  containerPort: 8000
  env:
    - name: LOG_LEVEL
      value: "INFO"

replicaCount: 1
