name: Merge

on:
  push:
    branches:
      - master
  pull_request:
    types: [closed]
    branches:
      - master

jobs:
    tests:
        uses: ./.github/workflows/tests.yml
        secrets:
            openai_key: ${{ secrets.OPENAI_KEY }}
            discord_webhook_url: ${{ secrets.DISCORD_WEBHOOK_URL }}

    version:
        needs: tests
        uses: ./.github/workflows/version.yml
        secrets:
            git_token: ${{ secrets.GPAT_TOKEN }}

    build-and-deploy:
        if: needs.version.outputs.version_bump == 'true'
        needs: version
        uses: ./.github/workflows/docker-image.yml
        secrets:
            dockerhub_username: ${{ secrets.DOCKERHUB_USERNAME }}
            dockerhub_token: ${{ secrets.DOCKERHUB_TOKEN }}
            repo_token: ${{ secrets.GPAT_TOKEN }}
            discord_webhook_url: ${{ secrets.DISCORD_WEBHOOK_URL }}
        with:
            version: ${{ needs.version.outputs.version }}