name: PR

on:
  pull_request:
    branches:
      - master
    types: [opened, synchronize, reopened]
  workflow_dispatch:

jobs:
  tests:
      uses: ./.github/workflows/tests.yml
      secrets:
          openai_key: ${{ secrets.OPENAI_KEY }}
          discord_webhook_url: ${{ secrets.DISCORD_WEBHOOK_URL }}
