name: Pytest

on:
  workflow_call:

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set env
        run: echo "ENV=test" >> $GITHUB_ENV

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libgtk-4-1 \
            libgraphene-1.0-0 \
            libwoff2dec1.0.2 \
            libvpx9 \
            libevent-2.1-7 \
            libopus0 \
            libgstreamer1.0-0 \
            libgstreamer-plugins-base1.0-0 \
            libflite1 \
            libavif16 \
            libharfbuzz-icu0 \
            libsecret-1-0 \
            libhyphen0 \
            libmanette-0.2-0 \
            libgles2 \
            libx264-163

      - name: Install pdm
        run: pip install pdm

      - name: Install project dependencies
        run: pdm install

      - name: Install playwright
        run: pdm run playwright install

      - name: Run tests
        run: PYTHONPATH=. pdm run pytest -v -ra api/backend/tests
        
