name: Pytest

on:
  workflow_call:

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: actions/setup-node@v3

      - name: Set env
        run: echo "ENV=test" >> $GITHUB_ENV

      - name: Install pdm
        run: pip install pdm

      - name: Install project dependencies
        run: pdm install

      - name: Install playwright
        run: pdm run playwright install --with-deps

      - name: Run tests
        run: PYTHONPATH=. pdm run pytest -v -ra api/backend/tests
        
